ao-libre/finisterra

- build.gradle
- client/build.gradle
- design/build.gradle
- desktop/build.gradle
- server/build.gradle
- shared/build.gradle
NOTE: i also removed the jlink plugin that isn't working.
> This way of adding plugins to a project is much more than a more convenient syntax. The plugins DSL is processed in a way which allows Gradle to determine the plugins in use very early and very quickly. This allows Gradle to do smart things such as:
> 
> - Optimize the loading and reuse of plugin classes.
> 
> - Allow different plugins to use different versions of dependencies.
> 
> - Provide editors detailed information about the potential properties and values in the buildscript for editing assistance.
> 
> This requires that plugins be specified in a way that Gradle can easily and quickly extract, before executing the rest of the build script. It also requires that the definition of plugins to use be somewhat static.
> 
> …
> Implement Plugins DSL.

- gradle/wrapper/gradle-wrapper.properties
Travis arrojaba un error de compilación que no nos permitía testear los cambios. La solución fue agregar el protocolo seguro en la url para descargar gradle.
> [fix-gradle-url] Ads protocol secure for download gradle

- build.gradle
- client/build.gradle
- components/build.gradle
- design/build.gradle
- desktop/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- server/build.gradle
- shared/build.gradle
- Todas las versiones de las dependencias ahora se manejan desde el `build.gradle` de la carpeta principal.
- Actualizo la version de gradle 5.6.2 -> 5.6.4.
- Actualizo las versiones de las dependencias.
- Ahora las declaraciones de dependencias son mas amigables visualmente.
- Se sustituyó la palabra clave obsoleta desde Gradle 3.0 `compile` al declarar dependencias. (@guidota , si podes echarle un vistazo y decirme que onda...)
Testeado y funcional.
> [gradle] [modifica] Actualizo gradle y mejora en manejo de versiones.

- desktop/Config.json
**Descripción:** renombre del servidor de New York (es Zephyr, no Zhepyr :) )
> Renaming New York servername

- client/src/game/managers/AOInputProcessor.java
- shared/resources/lang/messages_en_US.properties
- shared/resources/lang/messages_es_AR.properties
- shared/resources/lang/messages_es_US.properties
- shared/src/shared/util/Messages.java
Cambia el mensaje "no puedes atacar a ese objetivo" por "no puedes disparar tan rápido" cuando se usa repetidamente el ataque con arco en un intervalo muy corto de tiempo. 
cambios en los archivos de lenguaje según corresponde.
> cant shoot that fast reemplaza a cant attack en AOInputProsessor

- server/src/server/systems/combat/RangedCombatSystem.java
Arregla la falta de uso de energia al disparar las flechas.
Toma como ataque fallado al disparar a donde no hay objetivo.
> fix usar energía al disparar flechas

- client/src/game/handlers/DefaultAOAssetManager.java
- client/src/game/screens/GameScreen.java
- desktop/Config.json
**Descripción**:
En varias fases fuimos implementando el sonido. Al momento de realizar esta correción, se producían errores al querer correr el juego mediante un ejecutable y estos eran producto del sonido.
Encontramos el problema al asignar valores a la música y el sonido a través del assetmanager.
libgdx no reconocía los sonidos como cargados cuando se utilizaban los geters correspondientes y tiraba como resultado error en el assetmanager.
**Funcionalidad**:
- Lo solucionamos cambiando los return de getMusic y getSound por una forma en que  libgdx puede procesar correctamente.
- Activamos el sonido y agregamos música de fondo para poder testear.
- Ahora se reproducen los sonidos que ya estaban implementados: caminar y bloquear con escudo.
> Arreglo para poder crear release con sonidos

- design/src/design/screens/views/ImageView.java
- design/src/design/screens/views/View.java
Ahora son visibles las barras de desplazamiento en el design center.
Para todas las ventanas salvo el mapEditor (no esta montado sobre un scrollpane y todavía no entiendo cual es la parte que donde hay que incluirlo)
> Activada las scrollbar del  Design Center. (falta la de MapEditor)

- design/src/launcher/DesignCenter.java
Una simple linea impedia que se cierre. no se si fue cuando lo crearon que por alguna rason lo pusieron en false o por usar el autocompletado.
dispose() hasta donde entendi se usa para liberar los recursos usados
Closes #254
> Solucion error no anda el boton de cerrar el Finisterra Design Center

- client/src/game/handlers/DefaultAOAssetManager.java
- client/src/game/ui/GUI.java
- shared/src/shared/util/LogSystem.java
Al tratar de tomar un screenshot se crasheaba el juego.
El cliente trataba de generar un archivo cuyo nombre poseía caracteres inválidos para los estándares de los nombres de los archivos, en este caso, el `: (dos puntos)`.
Esto se arregla especificando un formato predeterminado donde la fecha y la hora que se va a guardar en el nombre de los `.png` solo use caracteres válidos.
El nombre de los `.png` de los screenshots (ahora) tienen el formato `ScreenShot-{fecha}_{hora}.png`
> Arreglado error al tomar screenshot.

- client/src/game/screens/CreateScreen.java
- client/src/game/screens/LoginScreen.java
- client/src/game/screens/SignUpScreen.java
Algunos botones parecían no funcionar o se deshabilitaban y no
volvían a habilitarse.
Ahora los botones usan ChangeListener. Internamente, se dispara
cuando en el botón se recibe un ClickListener.clicked() y está
habilitado.
Cuando se deshabilita un botón, se dispara un Timer para volver a
habilitarlo.
Afecta:
- CreateScreen
- LoginScreen
- SignUpScreen
Fixes #306
> Fix bug de botones

- client/src/com/badlogic/gdx/graphics/g2d/TextureArraySpriteBatch.java
Fixed AMD related bug where texture-array indexing extension being unsupported did not raise an compile error. This improves the detection of unsupported GPUs to safely fall back to a normal SpriteBatch.
Fuente: https://github.com/libgdx/libgdx/commit/40b6a13d32d5e6020ab336d8f1bd1c3e302cd858
> Fixed AMD desktop GPU extension detection bug.

- client/src/game/systems/resources/MapSystem.java
- client/src/game/systems/screen/MouseSystem.java
Chequea MapSystem.getTile(worldPos) por puntero null.
Agrega anotación @Nullable y warning (@todo Revisar).
Hago referencia a #322.
> Fix NullPointerException en MouseSystem

- client/src/game/systems/world/NetworkedEntitySystem.java
Arregla el método `NetworkedEntitySystem.existsLocal()` y se sacan los bloques Try/Catch. No debería fallar por NPE.
~~Try/Catch en NetworkedEntitySystem.unregisterLocalEntity() para no crashear por NPE:~~
```
java.lang.NullPointerException
at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
at game.systems.world.NetworkedEntitySystem.unregisterLocalEntity(NetworkedEntitySystem.java:40)
at game.systems.world.ClearSystem.process(ClearSystem.java:23)
at com.artemis.systems.IteratingSystem.processSystem(IteratingSystem.java:46)
at com.artemis.BaseSystem.process(BaseSystem.java:46)
at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
at …
```
> Fix NPE en NetworkedEntitySystem

- client/src/game/systems/resources/MapSystem.java
Floodea el log de errores con advertencias.
> Elimina Log.warn() de MapSystem.getTile()

- server/src/server/systems/CommandSystem.java
```
Fri Apr 24 16:54:55 ART 2020 [ERROR] [Command Parser] Error al ejecutar comando: /sethome
java.lang.IndexOutOfBoundsException: index can't be >= size: 17 >= 17
at com.badlogic.gdx.utils.Array.get(Array.java:154)
at server.systems.CommandSystem.lambda$new$3(CommandSystem.java:78)
at server.systems.CommandSystem.handleCommand(CommandSystem.java:127)
at server.network.ServerRequestProcessor.processRequest(ServerRequestProcessor.java:191)
at shared.network.interaction.TalkRequest.accept(TalkRequest.java:23)
at server.systems.ServerSystem.processJob(ServerSystem.java:50)
at server.systems.ServerSystem.processSystem(ServerSystem.java:63)
at com.artemis.BaseSystem.process(BaseSystem.java:46)
at com.artemis.InvocationStrategy.process(InvocationStrategy.java:25)
at …
```
> Hotfix IndexOutOfBounds en CommandSystem

- server/src/server/systems/world/entity/combat/MagicCombatSystem.java
Solución del hechizo inmovilizar, que no funcionaba ni consumía maná, tampoco funcionaban "Fuerza" y "Agilidad". Ya consumen maná. Además ya avisa cuando te quedas sin maná.
> #344 y #322 hechizo inmovilizar no funciona. Aviso de que no tiene maná

- server/resources/NPCs.dat
Posiblemente relacionado a #250 ya que cuando tenias el item inexistente en el inventario e intentabas equipar un item cualquiera, este no se equipaba.
> Removido drop de item que no existe

- client/src/game/screens/CharacterSelectionScreen.java
- client/src/game/systems/input/InputSystem.java
- client/src/game/systems/network/ClientResponseProcessor.java
- client/src/game/systems/network/ClientSystem.java
- server/src/server/systems/account/UserSystem.java
- server/src/server/systems/network/ServerRequestProcessor.java
- shared/src/shared/network/init/NetworkDictionary.java
- shared/src/shared/network/interfaces/DefaultRequestProcessor.java
- shared/src/shared/network/interfaces/IRequestProcessor.java
- shared/src/shared/network/interfaces/IResponseProcessor.java
- shared/src/shared/network/user/UserLogoutRequest.java
- shared/src/shared/network/user/UserLogoutResponse.java
Implementado pedir la desconexión al servidor
arregla (o eso creo) el problema de múltiples copias del jugador al reloguear sin cerrar el cliente
el botón "back to login" de la pantalla de selección de personajes ahora corta la conexión al servidor
> Pedir al servidor que te desconecte + arreglo multiples copias del pj

- client/src/game/screens/CharacterSelectionScreen.java
- client/src/game/systems/input/InputSystem.java
- client/src/game/systems/network/ClientResponseProcessor.java
- client/src/game/systems/network/ClientSystem.java
- server/src/server/core/ServerStrategy.java
- server/src/server/systems/account/AccountSystem.java
- server/src/server/systems/account/UserSystem.java
- server/src/server/systems/network/ServerRequestProcessor.java
- server/src/server/systems/network/ServerSystem.java
- shared/src/shared/network/init/NetworkDictionary.java
- shared/src/shared/network/interfaces/DefaultRequestProcessor.java
- shared/src/shared/network/interfaces/IRequestProcessor.java
- shared/src/shared/network/interfaces/IResponseProcessor.java
- shared/src/shared/network/user/UserLogoutRequest.java
- shared/src/shared/network/user/UserLogoutResponse.java
El servidor puede cerrar conexiones de manera unilateral. Cierra la conexión después de crear una cuenta.
El servidor mantiene una lista de usuarios conectados y chequea que el usuario no esté conectado al loguear.
Arregla el bug del botón jugar deshabilitado después de crear un PJ.
> Fix login y múltiples conexiones

- server/src/server/systems/network/ServerSystem.java
Captura paquetes internos a Kryonet (FrameworkMessage) que podrían
filtrase y entenderse como paquetes ilegales.
Vuelve a usar Artemis Fluid.
> Arreglos a ServerSystem
