core/src/ar/com/tamborindeguy/client/screens/LoginScreen.java, core/src/ar/com/tamborindeguy/client/systems/network/ClientSystem.java
Implemented with _SelectBox_.
```java
SelectBox<Hero> heroSelect = new SelectBox<Hero>(Skins.COMODORE_SKIN);
heroSelect.setItems(Hero.WARRIOR, Hero.MAGICIAN, Hero.ROGUE, Hero.PALADIN, Hero.PRIEST);
```
=> Hero selection in LoginScreen

build.gradle
Apply kotlin gradle plugin to design project
=> Fixing design project gradle build

README.md
Config Default and Config AlternativeTwo
=> Update Readme.md KeyToPlay

client/src/game/screens/GameScreen.java, client/src/game/systems/render/world/BuffRenderingSystem.java, components/src/entity/character/attributes/Agility.java, components/src/entity/character/attributes/Attribute.java, components/src/entity/character/attributes/Charisma.java, components/src/entity/character/attributes/Constitution.java, components/src/entity/character/attributes/Intelligence.java, components/src/entity/character/attributes/Strength.java, components/src/entity/character/states/Buff.java, components/src/entity/character/states/BuffTimeleftAgi.java, server/src/server/combat/AbstractCombatSystem.java, server/src/server/combat/MagicCombatSystem.java, server/src/server/combat/PhysicalCombatSystem.java, server/src/server/core/Server.java, server/src/server/systems/BuffSystem.java, server/src/server/systems/manager/CombatManager.java, server/src/server/systems/manager/ItemManager.java, server/src/server/systems/manager/WorldManager.java, shared/resources/spells/spells.json, shared/src/shared/model/Spell.java, shared/src/shared/network/init/NetworkDictionary.java
created new hierarchy for attributes now they inherit from a parent class called Attribute. This attribute class has a current value (that holds the original or the modified value) and a base value (the original value)
The buff component keeps track of the modified attributes and the effect time, and the buff system uses this component to update the effect time left, and to remove the already timed out effects.
closes #36
=> Buff system with Agility and Strength

gdd.md
Documento de diseño del juego en desarrollo.
Se Agregó en ficha técnica la ampliación de idiomas.
=> Create GDD.MD Move to /docs

README.md
Corrección de títulos y eliminación de texto innecesario
=> Arreglo de sintaxis en keyToPlay

client/src/game/systems/render/world/BuffRenderingSystem.java, shared/build.gradle
buff time left is now synced with server time
closes #44
=> Buff gui indicator #44

README.md
Added some tips to run the project easily
=> Added some tips to run the project easily

client/src/game/AOGame.java, client/src/game/handlers/AssetHandler.java, desktop/src/launcher/DesktopLauncher.java
=> Implemented proper method to close the application.

components/src/entity/npc/OriginPos.java, components/src/entity/npc/Respawn.java, server/src/server/combat/MagicCombatSystem.java, server/src/server/combat/PhysicalCombatSystem.java, server/src/server/core/Server.java, server/src/server/systems/ai/PathFindingSystem.java, server/src/server/systems/ai/RespawnSystem.java, server/src/server/systems/manager/WorldManager.java, shared/src/shared/network/init/NetworkDictionary.java
=> Respawn system

docs/gdd.md
Se agregaron definiciones de idioma para la documentación
=> Definiciones de idiomas

README.md
=> Update Alternative keys

desktop/build/releases/start.md
este directorio es utilizado para almacenar los datos de las releases
=> dependencia de carpeta para gradlew

npc-guardian.md
Requiere de una parte técnica: Funcionales (desde 0) , una parte artística: Diseño visual y animaciones(desde 0), una parte narrativa: Diálogos (mejoras)
=> Propuesta Npc Guardián

server/Server.json
se corrigió el puerto de conexión del servidor
=> puerto correcto para el uso en localhost

server/Server.json, server/resources/NPCs.dat, server/src/server/systems/combat/MagicCombatSystem.java
Modificación de la ecuación de calculo de daño mágico. 
Al usar magia ahora también otorga experiencia
=> Mejoras al sistema de combate mágico

server/src/server/database/model/modifiers/Modifiers.java, server/src/server/systems/CharacterTrainingSystem.java
faltaba definir en la tabla de modificadores Puntería de WRESTLING y PROJECTILE lo cual provocaba un error en la lectura de datos del array y no otorgaba vida al subir de nivel
=> Level up doesn't give more HP

client/src/game/managers/AOInputProcessor.java, client/src/game/network/GameNotificationProcessor.java, client/src/game/screens/GameScreen.java, client/src/game/systems/render/world/TargetRenderingSystem.java, client/src/game/ui/GUI.java, client/src/game/ui/SpellView.java
Fixes:
- Issues when reentering game after ESC exit.
- GUI not drawing after reentrance.
=> non-static GUI

client/src/game/systems/network/ClientSystem.java
=> game.toLogin() as runnable

.gitignore, client/src/game/ui/GUI.java, desktop/build.gradle
This PR is just a little fix i forgot to apply to #146 .
Before, we were bundling the app with the modules provided by JDK 14, an unstable release of Java.
Now, we bundle the app with our current JDK.
=> [PATCH] Manual JPackage implementation.

client/src/game/network/ClientResponseProcessor.java, client/src/game/network/GameNotificationProcessor.java, client/src/game/screens/GameScreen.java, client/src/game/systems/render/world/TargetRenderingSystem.java, client/src/game/ui/GUI.java, client/src/game/ui/Inventory.java, client/src/game/ui/SpellView.java, client/src/game/utils/WorldUtils.java, desktop/build.gradle
=> Fixing NPE when creating GUI view. (not tested)

client/src/game/managers/AOInputProcessor.java, client/src/game/ui/GUI.java
Toggle between Windowed Mode and Fullscreen by pressing the `F11` key.
=> Fullscreen support.

client/src/game/ui/GUI.java
Now it returns to the Windowed Mode with its previous window size.
=> Fix window resolution after fullscreen.

desktop/build.gradle, server/src/server/systems/EntityFactorySystem.java
En este PR agregamos los commit correspondientes a los ajustes menores de Factoria que permitan una mejor experiencia en la pre-release 0.1.12
=> Ajustes de factoria y correcciones menores - Pre release

design/src/design/screens/map/MapEditor.java
La cámara ahora se mueve con mayor fluidez al recorrer el mapa con SCROLL o SHIFT + SCROLL mouse
=> fix the map editor camera

README.md, docs/get-started/development-environment.md, docs/get-started/key-config-to-play.md, docs/get-started/run-on-console.md, docs/get-started/workflow-github.md
- Se reformuló la página de inicio.
- Se agregó una imagen de los colaboradores (reclamen su lugar si nos hemos olvidado de alguno xD, sory)
- Se segmento la documentación del get-started
- Se actualizaron los enlaces de las redes
=> Mejoras para la documentación

client/src/game/ui/user/UserImage.java
Cambio a la formula para calcular la experiencia en la barra de experiencia circular y al tamaño de la misma.
Añade  la barra circular de exp. al UI del personaje
=> [MODIFICA]  user image [AÑADE] Barra circular de experiencia

.github/FUNDING.yml
Ahora se puede donar al proyecto por medio de Ko fi
=> added ko-fi sponsor

desktop/Config.json
- Agregamos servidor mantenido por @luksdlt92 en NewYork
Requiere de #215
Objetivo probar latencia, estabilidad y compensación.
=> Agregamos servidor NewYork

client/src/game/screens/LobbyScreen.java, server/Server.json, server/src/server/ServerConfiguration.java, server/src/server/core/Finisterra.java, server/src/server/network/FinisterraRequestProcessor.java, shared/src/shared/model/lobby/Lobby.java, shared/src/shared/network/lobby/CreateRoomRequest.java
Antes:
```Se enviaba una peticion al servidor con el limite máximo de jugadores en una sala```
Ahora:
```Se establece el limite máximo de jugadores desde el Server.json```
=> Limite máximo de jugadores online en una sala.

client/src/game/screens/RoomScreen.java, server/src/server/network/FinisterraRequestProcessor.java, shared/src/shared/model/lobby/Player.java
**Descripción:** al entrar en una sala, la selección del héroe es aleatoria. Aún así, puede seleccionarse el héroe deseado al ingresar al servidor.
**Funcionamiento:**
1. Se elimina el seteo del héroe al crear el jugador, dado que el concepto de héroe no debería aparecer hasta la sala (conceptualmente).
2. Al entrar en la sala, se selecciona un héroe al azar.
3. El jugador puede elegir el héroe que quiera y se respetará al iniciar en el juego.
**Nota:** este pull request reemplaza https://github.com/ao-libre/ao-java/pull/217 el cual fue tomado como base.
=> Default hero selection

.github/FUNDING.yml, .travis.yml, client/src/game/ui/user/UserImage.java
**Descripción:**
Cuando migramos #211 perdimos algunos cambios que ya habían sido migrado a master.
**Funcionamiento:**
Volvemos agregar los cambios que se habían perdido
**Nota:**
Este pull request repara [176e631](https://github.com/ao-libre/ao-java/commit/176e631096effe6c52e114929772f49226aaece0)
=> Fix commit 176e631

.github/ISSUE_TEMPLATE/docu-report.md
**Descripción**
Estamos desarrollando la wiki-documentación de desarrollo y en ella vamos agregar un enlace para reportar un error que direccionará al template.
**Funcionamiento**
Creamos un template para reportar un error en la documentación.
=> Agregamos template-Issue para reportar errores en la docu

client/src/game/ui/Inventory.java
se cambio el cursor "select" por el cursor "arrow" cuando se prepara a disparar
=> cambiado cursor select cuando se prepara a disparar por el cursos arrow

desktop/Config.json
En este servidor se mantendrá online la version del servidor de la última release (Release Server)
Mientras que en (Alpha Server) se actualizará de vez en cuando en función a los cambios realizados en la rama master.
=> Nuevo servidor Release.

.github/ISSUE_TEMPLATE/otro-reporte-.md, .github/ISSUE_TEMPLATE/reporte-de-la-documentaci-n-.md, .github/ISSUE_TEMPLATE/reporte-de-la-documentaci-n.md, .github/ISSUE_TEMPLATE/reporte-del-juego-.md, .github/ISSUE_TEMPLATE/reporte-t-nico-.md
- Documentación
- Juego
- Técnico
- Otros
=> Agregamos plantillas para tipos de issue

build.gradle, shared/build.gradle
Actualizamos la version de la api que serializa los datos de los objetos.
Testeada y Funcional.
=> Updated Kryo version 2.24.0 -> 4.0.2

server/src/server/core/Server.java, server/src/server/network/ServerRequestProcessor.java, server/src/server/systems/CommandSystem.java, server/src/server/systems/ServerSystem.java, shared/resources/lang/messages_en_US.properties, shared/resources/lang/messages_es_AR.properties, shared/resources/lang/messages_es_US.properties, shared/src/shared/util/Messages.java
**Descripción:** se agrega soporte básico para comandos dentro del juego por medio de la consola utilizando como ejemplo un comando para saber los jugadores online. A futuro deberían restringirse por privilegios del usuario.
**Funcionamiento:**
1. Se envía un mensaje por consola que comienza con el caracter '/' (significa que es un comando). Ese mensaje es un TalkRequest.
2. Del lado del servidor, se corrobora si el mensaje empieza con '/' identificando si es un comando.
3. En caso de ser un comando, es handleado por el CommandSystem, devolviendo una respuesta (si es que aplica, lógicamente).
=> Implementación de comandos (básico)

README.md
Se agrego una pequeña seccion en el `readme.md` para poder correr el proyecto rapidamente.
=> Added a quick start to run the project

docs/index/Español/ChangeLog.txt
Aclaración: esta información es solo válida para el changelog en español.
**Descripción**
Terminamos de definir como será nuestro changelog basado en [mantenga un change log](https://keepachangelog.com/es-ES/1.0.0/).
Sumamos también un parámetro que unifique las forma de expresarnos. Al momento de mencionar un cambios usamos el plural. Ej, Agregamos, eliminamos, modificamos.
Esto se debe a que para que sea posible cualquier mejora en nuestro proyecto, se requiere de otros corrientes de vida que están al servicio del mantenimiento de servidores, módulos que permiten que creemos el juego, sugerencias, observaciones, tutoriales y blogs, etc. El recorrido, conforma un todo, por eso lo interpretamos así.
**Funcionamiento**
Cuando estamos creando mejora o corrección de cualquier índole, al …
=> Actualizamos changeLog

components/src/entity/character/equipment/Helmet.java, components/src/entity/character/equipment/Shield.java, components/src/entity/character/equipment/Weapon.java, components/src/entity/world/Dialog.java, components/src/physics/AOPhysics.java, desktop/src/launcher/DesktopLauncher.java
Este es un PR de "rutina", donde escaneo projecto por proyecto el codigo para ver si hay formas de mejorarlo ya sea para incremetar su rendimiento, aumentar su encapsulamiento, arreglar alguna que otra "villereada" que encuentre e implementar los consejos que me tira el PR (esta principalmente).
=> Minor improvements components proyect.

client/src/game/AOGame.java, client/src/game/ClientConfiguration.java, client/src/game/handlers/MusicHandler.java, client/src/game/handlers/SoundsHandler.java, client/src/game/loaders/AOSkinLoader.java, client/src/game/network/GameNotificationProcessor.java, client/src/game/network/KryonetClientMarshalStrategy.java, client/src/game/screens/GameScreen.java, client/src/game/screens/LoadingScreen.java, client/src/game/systems/render/world/BuffRenderingSystem.java, client/src/game/ui/GUI.java, design/src/design/designers/ImageDesigner.java, design/src/design/designers/NPCDesigner.java, design/src/design/screens/views/DescriptorView.java, design/src/launcher/DesignCenter.java, desktop/src/launcher/CreatorLauncher.java, desktop/src/launcher/DesktopLauncher.java, server/src/server/core/Finisterra.java, server/src/server/core/Server.java, server/src/server/core/ServerStrategy.java, server/src/server/manager/ConfigurationManager.java, server/src/server/systems/manager/ObjectManager.java, server/src/server/systems/manager/SpellManager.java, shared/src/shared/model/readers/Reader.java, shared/src/shared/util/LogSystem.java, shared/src/shared/util/MapHelper.java
***Cosas a tener en cuenta a partir de ahora:***
- ***NO*** usar `e.printStackTrace()`. Usar `Log.error("Mensaje de error", e)`
- ***NO*** registrar errores con `Log.info()` (especialmente en los bloques try-catch).
- Todos los logs ***a excepción de los que estan registrados con `Log.info()` y `Log.debug()`*** se guardarán en un archivo `Errores.log` en el directorio donde esta el ejecutable.
- ***NO*** usar solo `Log.info()` y  `Log.error()`, usar también `Log.warn()`, `Log.trace()`, `Log.debug()` según el caso.
=> Refactor logging system.

client/src/game/managers/AOInputProcessor.java
**Antes**
* Enviamos a consola el nombre y la cantidad de los objetos en la posición del piso donde se hace click.
* Enviamos a consola si hay un npc o personaje. Sobre un objeto solo dice el nombre del npc o personaje.
**se agrega**
* objetos que están en los tiles del mapa, como por ejemplo arboles, depósitos de minerales, puertas, carteles, etc.
=> Mejora el mensaje en consola cuando se hace click sobre una posición del mapa. Actualización

client/src/game/ui/Slot.java, shared/resources/lang/messages_en_US.properties, shared/resources/lang/messages_es_AR.properties, shared/resources/lang/messages_es_US.properties, shared/src/shared/util/Messages.java
**Muestra:**
* Nombre, Tipo, Valor y Cantidad para todos los objetos.
* Para Armas
la clase
* Para armas y flechas
daño máximo y mínimo
* Para armaduras, cascos y escudos
defensa  máxima  y mínima.
* Para las pociones
el máximo y mínimo de recuperación
el tiempo de efecto
Hechas las  traducciones del texto correspondientes.
=> Implementacion de Tooltip para Items

.gitignore, client/src/game/AOGame.java, client/src/game/ClientConfiguration.java, client/src/game/handlers/MusicHandler.java, client/src/game/handlers/SoundsHandler.java, client/src/game/loaders/AOSkinLoader.java, client/src/game/network/GameNotificationProcessor.java, client/src/game/network/KryonetClientMarshalStrategy.java, client/src/game/screens/GameScreen.java, client/src/game/screens/LoadingScreen.java, client/src/game/systems/render/world/BuffRenderingSystem.java, client/src/game/ui/GUI.java, design/src/design/designers/ImageDesigner.java, design/src/design/designers/NPCDesigner.java, design/src/design/screens/views/DescriptorView.java, design/src/launcher/DesignCenter.java, desktop/src/launcher/CreatorLauncher.java, desktop/src/launcher/DesktopLauncher.java, server/src/server/core/Finisterra.java, server/src/server/core/Server.java, server/src/server/core/ServerStrategy.java, server/src/server/manager/ConfigurationManager.java, server/src/server/systems/manager/ObjectManager.java, server/src/server/systems/manager/SpellManager.java, shared/src/shared/model/readers/Reader.java, shared/src/shared/util/LogSystem.java, shared/src/shared/util/MapHelper.java
Esta es una re-subida de #257 con 2 errores arreglados.
- No se detectaba bien el tipo de log registrando en el archivo .log las entradas de tipo INFO.
- Agregada compatibilidad con el salto de linea de Windows, `\r\n`.
=> Refactor logging system (Arreglado)

client/src/game/managers/AOInputProcessor.java, client/src/game/systems/render/world/CombatRenderingSystem.java, client/src/game/systems/render/world/MapGroundRenderingSystem.java, design/src/design/designers/AnimationDesigner.java, server/src/server/systems/combat/PhysicalCombatSystem.java, server/src/server/systems/combat/RangedCombatSystem.java, settings.gradle, shared/src/shared/interfaces/CharClass.java, shared/src/shared/interfaces/Hero.java, shared/src/shared/interfaces/Race.java
Estaría bueno hacer que el juego pueda compilarse/ejecutarse en Java 8 por si alguno no le gusta el JDK actual, o mas importante, quiere ejecutar el juego en android jejeje :cat:
=> Retro-compatibilidad con Java 8

client/src/game/managers/AOInputProcessor.java, client/src/game/screens/LoginScreen.java, client/src/game/screens/transitions/FadingGame.java, desktop/src/launcher/DesktopLauncher.java, gradle.properties
Fixes #266 , sin embargo @cpbeto me gustaría que te fijes otro tamaño minimo ya que en 800x600 se ve deformado. Considerá tambien que los gráficos fueron escalados 2X por lo que no se va a ver igual que en el AO hecho en VB6.
=> Fixes, pequeño refactor & limitado el tamaño mínimo de la ventana del juego.

client/src/game/AOGame.java, client/src/game/loaders/AOSkinLoader.java, client/src/game/screens/GameScreen.java, client/src/game/systems/camera/CameraShakeSystem.java, client/src/game/systems/network/ClientResponseProcessor.java, client/src/game/systems/network/ClientSystem.java, client/src/game/systems/network/GameNotificationProcessor.java, client/src/game/systems/network/KryonetClientMarshalStrategy.java, client/src/game/systems/render/BatchRenderingSystem.java, client/src/game/systems/render/world/CombatRenderingSystem.java, client/src/game/systems/render/world/DialogRenderingSystem.java, client/src/game/systems/render/world/NameRenderingSystem.java, client/src/game/systems/resources/AnimationsSystem.java, client/src/game/systems/screen/MouseSystem.java, client/src/game/systems/ui/action_bar/ActionBarSystem.java, client/src/game/systems/ui/console/ConsoleSystem.java, server/src/server/systems/manager/WorldManager.java
To avoid console flooding.
Extra: moving shake logic to corresponding system
=> Log.info -> Log.debug

design/src/design/graphic/AOImageActor.java
Reparamos un error que no permitia la carga correcta ciertas imagen como tileset
=> Fix design center

client/src/game/systems/physics/MovementProcessorSystem.java, client/src/game/systems/physics/MovementSystem.java, server/src/server/core/Finisterra.java, server/src/server/network/ServerRequestProcessor.java, server/src/server/systems/entity/MovementSystem.java, server/src/server/systems/user/ItemActionSystem.java, server/src/server/systems/user/PlayerActionSystem.java
Muevo el comportamiento de algunos paquetes grandes a sistemas sacando la logica de susodicha clase.
=> Simplifico el ServerRequestPreocessor.

client/src/game/systems/ui/dialog/DialogSystem.java, server/src/server/database/Account.java, server/src/server/network/ServerRequestProcessor.java, server/src/server/systems/CommandSystem.java, shared/resources/lang/messages_en_US.properties, shared/resources/lang/messages_es_AR.properties, shared/resources/lang/messages_es_US.properties, shared/src/shared/objects/factory/POJO.java, shared/src/shared/util/Messages.java
=> Refactor - Sistema de parseo de comandos.

client/src/game/systems/screen/MouseSystem.java, server/src/server/systems/combat/PhysicalCombatSystem.java
Al hacer click ahora también nos dice si hay arboles, puertas, minerales, carteles, portales  y otros objetos contenidos por los tiles.
fix random out of bounds en phisical combat system
=> Ver mas cosas + fix random out of bounds en phisical combat system

client/src/game/ClientConfiguration.java, client/src/game/screens/LoginScreen.java, client/src/game/systems/resources/MusicSystem.java
Este patch solo soluciona la interposición de músicas que se producía.
Ahora solo reproducimos una música.
Todo: mejorar el sistema.
=> Fix music System

client/src/game/screens/LoginScreen.java, client/src/game/systems/resources/MusicSystem.java
usamos preferences de libGDX para guardar las preferencias de audio
genera un archivo en
Windows	                 %UserProfile%/.prefs/Finisterra
Linux y OS X	        ~/.prefs/Finisterra
=> Ahora se guardan las preferencias de sonido de audio

client/src/game/screens/LoginScreen.java, client/src/game/screens/SignUpScreen.java, client/src/game/systems/network/ClientSystem.java
Resuelve @todo en LoginScreen y SignUpScreen.
=> Encapsula conexión al servidor en ClientSystem.connect()

client/src/com/badlogic/gdx/graphics/g2d/TextureArraySpriteBatch.java
This reverts commit 17b35a2ff7d8371741a544af85c5fd3eb4c92c18.
=> Revert "Fixed AMD desktop GPU extension detection bug. (#311)"

client/src/game/AOGame.java, client/src/game/handlers/DefaultAOAssetManager.java, client/src/game/screens/LoginScreen.java, client/src/game/screens/ScreenManager.java, client/src/game/systems/input/InputSystem.java, client/src/game/systems/resources/MusicSystem.java
soluciona el problema de la superposición de la música.
=> fix superposicion de musica

client/src/game/systems/resources/MusicSystem.java
Ahora pausa y reproduce la música actual
=> Corregimos MusicSystem.toggle()

client/src/game/AOGame.java, client/src/game/screens/LoadingScreen.java
NPE al cerrar la aplicación si no había terminado de cargar (estando en LoadingScreen).
=> Fix NPE en AOGame.dispose

CHANGES.md, client/src/game/screens/CharacterScreen.java, client/src/game/screens/CharacterSelectionScreen.java, client/src/game/screens/CreateScreen.java, client/src/game/screens/LoadingScreen.java, client/src/game/screens/LoginScreen.java, client/src/game/screens/SignUpScreen.java, client/src/game/systems/render/world/CombatRenderingSystem.java, client/src/game/systems/render/world/DialogRenderingSystem.java, client/src/game/systems/render/world/NameRenderingSystem.java, client/src/game/systems/ui/action_bar/ActionBarSystem.java, client/src/game/systems/ui/action_bar/systems/InventorySystem.java, client/src/game/systems/ui/stats/StatsSystem.java, client/src/game/ui/AOConsole.java, client/src/game/ui/DialogText.java, client/src/game/ui/Inventory.java, client/src/game/ui/SpellBookUI.java, client/src/game/ui/SpellSlot.java, client/src/game/ui/SpellSlotEC.java, client/src/game/ui/SpellView.java, client/src/game/ui/SpellViewExpanded.java, client/src/game/ui/SwitchButtons.java, client/src/game/ui/WidgetFactory.java, client/src/game/ui/user/Bar.java, client/src/game/ui/user/UserImage.java, client/src/game/utils/Colors.java, design/src/design/screens/views/NPCView.java
- Para simplificar la creacion de widgets y saber que hace falta implementar en caso de crear nuevos skins.
=> Adding WidgetFactory

client/src/game/screens/CharacterSelectionScreen.java, client/src/game/systems/network/ClientResponseProcessor.java, server/src/server/systems/account/AccountSystem.java, server/src/server/systems/account/UserSystem.java, shared/src/shared/network/account/AccountLoginResponse.java
* Ahora muestra la imagen del personaje según su clase
* Se muestra el hp y mp mínimo y máximo del personaje
=> Actualización de la pantalla de selección de personaje

client/src/com/badlogic/gdx/graphics/g2d/ArrayTextureSpriteBatch.java, client/src/game/systems/render/BatchRenderingSystem.java, desktop/src/launcher/DesktopLauncher.java, gradle/wrapper/gradle-wrapper.properties
Activo el uso de OpenGLES 3.2 xq es requerido según el creador de la implementacion.
=> Actualizo la clase TextureArraySprteBatch

server/src/server/systems/world/entity/combat/PhysicalCombatSystem.java
=> Implementado golpe critico

.gitignore, client/src/game/screens/LoginScreen.java, client/src/game/screens/ScreenManager.java, client/src/game/systems/network/ClientResponseProcessor.java, server/src/server/core/Finisterra.java, server/src/server/database/Account.java, server/src/server/database/Charfile.java, server/src/server/systems/account/AccountSystem.java, server/src/server/systems/account/UserSystem.java, server/src/server/systems/config/NPCSystem.java, shared/resources/lang/messages_en_US.properties, shared/resources/lang/messages_es_AR.properties, shared/resources/lang/messages_es_US.properties, shared/src/shared/network/account/AccountLoginResponse.java, shared/src/shared/network/user/UserLoginResponse.java, shared/src/shared/util/AccountSystemUtilities.java, shared/src/shared/util/Messages.java
NOTA: La creación de las carpetas necesarias para el sistema de cuentas se hace en un thread aparte mientras se inicializa el servidor.
=> Chequeamos y creamos las carpetas `CharFiles` y `Accounts` el iniciar el servidor.

client/src/game/screens/CharacterSelectionScreen.java, server/src/server/systems/account/UserSystem.java, server/src/server/systems/world/WorldEntitiesSystem.java, server/src/server/systems/world/WorldSaveSystem.java
- Agregamos un parámetro Runnable en `UserSystem#save(int, Runnable)` para ejecutar código DESPUES de haber guardado el charfile. (@guidota )
- Agrego vallidación para ver si la lista de componentes esta vacía antes de hacer output en el archovo .json
=> Fix: Los charfiles se guardaban vacíos.

client/src/game/screens/CharacterSelectionScreen.java
=> FIX: tiempo minimo para volver a logear

build.gradle, server/Server.json, server/build.gradle
Expone la propiedad `buildVersion` a todos los proyectos del repositorio. Agrega la propiedad 'version' al `Server.json` y la expande durante la etapa de `bundle`.
=> Fix #221: Added buildVersion string to Gradle script(s). Added version tag to Server.json. Expand version upon server binary bundle.

client/src/game/screens/LoginScreen.java, client/src/game/ui/WidgetFactory.java, desktop/assets/data/ui/ao-skin-2/ao-skin.atlas
mismos arreglos que al login screen de la rama de desarrollo v1.15 pero para esta rama por si no les convence el cambio a la otra.
*agregado panel desplazable
*agregado nombre del servidor a la ventana de agregar servidores
*no se pueden duplicar entradas en la lista de servidores (solo si tienen el mismo nombre, dirección y puerto se considera igual)
*fix múltiples cuadro de diálogos al apretar repetidamente ESCAPE
*fix El slider de volumen funciona bien pero no se muestra bien, solo baja hasta el 80%.
=> Login Screen updates and fixes [Develop Branch]
